# Generated by Django 5.2.5 on 2025-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tweets/media/'),
        ),
    ]
